### ISSUE TITLE
opusenc: Unsupported FLAC input file

### ISSUE THREAD

**Issue by andreipoe** [xiph/opus-tools#66]
opusenc fails on some input FLAC files with a generic error:

```
$ opusenc --bitrate 160 1.{flac,opus}
Error: unsupported input file: 1.flac

$ file 1.flac
1.flac: Audio file with ID3 version 2.4.0, contains:FLAC audio bitstream data, 24 bit, stereo, 96 kHz, 28360569 samples
```

These FLAC files play without issue and are verified ok by `flac -t`.

```
$ opusenc --version
opusenc opus-tools 0.2 (using libopus 1.3.1)
Copyright (C) 2008-2018 Xiph.Org Foundation
```

**Comment by mark4o** [comment]
Fixed in 5d0ac2030244b33bf12512267fe62ffe831bf105

**Comment by andreipoe** [comment]
Thanks for your work on this @mark4o. I've tried a fresh build from the latest source code with the same files and I'm still seeing the same error. I suspect it might be related to the 24 bit/96 kHz quality; I've never encountered the issue with 16-bit files.
